services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - /Users/hazel/docker-demo/mysql8:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/hazel/docker-demo/redis:/data
